# pyhton_ddos_attack_test

A test I did to try to replicate a DDoS attack thru a multithread Python script 
